"use client";
import {useState,useMemo,useEffect} from "react";
import {LineChart,Line,CartesianGrid,XAxis,YAxis} from "recharts";
import {ChartContainer,ChartTooltip,ChartTooltipContent} from "@/components/ui/chart";
import {Switch} from "@/components/ui/switch";
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";
import {Plus,ArrowDownRight,ArrowUpRight,Trash2,Eye,Download,TrendingUp} from "lucide-react";
import {RecordItem,Benchmark,sampleRecords,STATIONS,fmt,total,metric,comparable,dateKey,download} from "@/lib/rox";
import {Button,Panel,Pick,EmptyBox,Stat,External} from "./ui";
export default function AnalysisView({records,benchmarks,onRecord,onManual,remove}:{records:RecordItem[];benchmarks:Benchmark[];onRecord:(r:RecordItem)=>void;onManual:()=>void;remove:(kind:string,id:string,title:string)=>void}){
 const [demo,setDemo]=useState(false),samples=useMemo(sampleRecords,[]),[aId,setAId]=useState(""),[bId,setBId]=useState(""),[kind,setKind]=useState("total"),[range,setRange]=useState("all");
 const source=demo?samples:records;
 const all=[...source].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)),a=all.find(r=>r.id===aId)||all[0],b=bId==="none"||bId.startsWith("bench-")?undefined:all.find(r=>r.id===bId)||all.find(r=>r.id!==a?.id&&a&&comparable(r)===comparable(a));
 const bench=benchmarks.find(x=>`bench-${x.id}`===bId),validPair=!!(a&&b&&comparable(a)===comparable(b)&&a.load!=="负重未填写"),series=all.filter(r=>a&&comparable(r)===comparable(a)&&r.complete&&(range==="all"||(Date.now()-new Date(r.date+"T12:00:00").getTime())/86400000<=Number(range))).sort((x,y)=>x.date.localeCompare(y.date)).map(r=>({date:r.date.slice(5),value:metric(r,kind),name:r.name})).filter(r=>r.value!==null),start=series[0]?.value,last=series.at(-1)?.value,improve=start!==null&&last!==null&&start!==undefined&&last!==undefined&&series.length>1?start-last:null;
 const best=series.length?Math.min(...series.map(r=>r.value!)):null,rows=[{id:"run",name:"8 段跑步"},...STATIONS.map(s=>({id:s.id,name:s.name})),{id:"zone",name:"转换区"},{id:"total",name:"总成绩（含罚时）"}],hasComparison=a&&(bench||b);
 return <div><div className="analysis-toolbar row space-between"><label className="row"><Switch checked={demo} onCheckedChange={v=>{setDemo(v);setAId("");setBId("")}}/>预览示例数据</label><Button onClick={onManual}><Plus/>补录成绩</Button></div>{demo&&<div className="notice">当前显示虚构示例，用于体验对比功能。不会计入你的训练记录。</div>}
 {!all.length?<EmptyBox title="每次训练，都可以看见进步" text="先完成一次计时或补录成绩；也可以开启示例数据，查看趋势和分段对比。" action={<Button onClick={()=>setDemo(true)}>查看示例分析<TrendingUp/></Button>}/>:<>
 <div className="analysis-filters"><div><label>当前训练</label><Pick value={a?.id||""} label="当前训练" options={all.map(r=>({value:r.id,label:`${r.date} · ${r.name} · ${r.athlete}`}))} onChange={v=>{setAId(v);setBId("")}}/></div><div><label>分析项目</label><Pick value={kind} label="分析项目" options={[{value:"total",label:"总成绩"},{value:"run",label:"跑步合计"},...STATIONS.map(s=>({value:s.id,label:s.name})),{value:"zone",label:"转换区"}]} onChange={setKind}/></div><div><label>时间范围</label><Pick value={range} label="时间范围" options={[{value:"all",label:"全部时间"},{value:"30",label:"近 30 天"},{value:"90",label:"近 90 天"}]} onChange={setRange}/></div></div>
 <div className="stats-grid three"><Stat label="所选条件最佳成绩" value={best!==null?fmt(best):"—"} detail={`${series.length} 次已完成记录`} accent/><Stat label="首末记录变化" value={improve===null?"—":`${improve>=0?"−":"+"}${fmt(Math.abs(improve))}`} detail={improve===null?"至少需要两次可比较记录":`${improve>=0?"用时减少":"用时增加"} ${start?Math.abs(improve/start*100).toFixed(1):0}%`}/><Stat label="当前记录" value={a&&metric(a,kind)!==null?fmt(metric(a,kind)!):"—"} detail={a?`${a.division} · ${a.complete?"已完成":"未完成"}`:""}/></div>
 <Panel title="时间进步趋势" eyebrow="PROGRESS OVER TIME" action={<span className="tag">越低越快</span>}>{series.length>1?<ChartContainer config={{value:{label:"用时",color:"#e96a34"}}} className="trend-chart"><LineChart data={series} margin={{left:12,right:18,top:15,bottom:10}}><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={12}/><YAxis width={62} domain={["auto","auto"]} tickFormatter={v=>fmt(Number(v))} tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent formatter={(v)=><span className="mono">{fmt(Number(v))}</span>}/>}/><Line dataKey="value" type="linear" stroke="#e96a34" strokeWidth={3} dot={{r:4,fill:"#e96a34"}} activeDot={{r:6}}/></LineChart></ChartContainer>:<EmptyBox title="再记录一次，就能看趋势" text="趋势按同一运动员、模式、组别、目标与填写的负重条件筛选。"/>}<p className="helper">当前条件：{a?.mode==="full"?"全程模拟":a?.mode==="single"?"单站训练":a?.mode==="race"?"比赛日":"裁判记录"} · {a?.load}。场地摩擦与器械差异仍可能影响用时。</p></Panel>
 <Panel title="分段横向对比" eyebrow="SPLIT BY SPLIT" action={<div className="compare-pick"><Pick label="对比对象" value={bench?`bench-${bench.id}`:b?.id||"none"} onChange={setBId} options={[{value:"none",label:"选择对比记录"},...all.filter(r=>r.id!==a?.id).map(r=>({value:r.id,label:`${r.date} · ${r.name}`})),...benchmarks.map(r=>({value:`bench-${r.id}`,label:`运动员 · ${r.name}`}))]}/></div>}>
 {hasComparison?<><div className={`comparison-note ${bench||!validPair?"notice":""}`}>{bench?`运动员参考：${bench.name} · ${bench.division}。仅用于了解差距，不能视为相同训练条件。`:validPair?"两次记录填写的组别、模式、负重和目标一致。差值为当前减去对照。":"两次记录的运动员或标准不同，或负重未填写。可以查看时间，但不计为严格的进步比较。"}{bench&&<External href={bench.source}>成绩来源</External>}</div><Table><TableHeader><TableRow><TableHead>项目</TableHead><TableHead className="text-right">当前</TableHead><TableHead className="text-right">{bench?bench.name:"对照"}</TableHead><TableHead className="text-right">差值</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=>{const av=metric(a!,row.id),bv=bench?(row.id==="total"?bench.seconds:bench.splits[row.id]??null):b?metric(b,row.id):null,diff=av!==null&&bv!==null?av-bv:null;return <TableRow key={row.id}><TableCell>{row.name}</TableCell><TableCell className="text-right mono">{av===null?"—":fmt(av)}</TableCell><TableCell className="text-right mono">{bv===null?"—":fmt(bv)}</TableCell><TableCell className={`text-right mono ${diff!==null&&diff<0?"green-text":diff!==null&&diff>0?"red-text":""}`}>{diff===null?"—":`${diff>0?"+":diff<0?"−":""}${fmt(Math.abs(diff))}`}</TableCell></TableRow>})}</TableBody></Table></>:<EmptyBox title="选择第二次训练或运动员" text="添加另一条记录，查看每个项目快了或慢了多少。"/>}</Panel>
 </>}
 <Panel title="训练记录" action={records.length>0?<Button variant="outline" onClick={()=>download("rox-training-records.json",JSON.stringify(records,null,2))}><Download/>导出记录</Button>:undefined}>{records.length?<Table><TableHeader><TableRow><TableHead>训练 / 日期</TableHead><TableHead>运动员</TableHead><TableHead>组别</TableHead><TableHead>成绩</TableHead><TableHead>状态</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{[...records].sort((a,b)=>b.date.localeCompare(a.date)).map(r=><TableRow key={r.id}><TableCell><b>{r.name}</b><small className="block muted">{r.date}</small></TableCell><TableCell>{r.athlete}</TableCell><TableCell>{r.division}</TableCell><TableCell className="mono">{fmt(total(r))}</TableCell><TableCell><span className={`tag ${r.complete?"green":""}`}>{r.complete?"已完成":"未完成"}</span></TableCell><TableCell><div className="row justify-end"><Button size="icon" variant="ghost" aria-label="查看记录" onClick={()=>onRecord(r)}><Eye/></Button><Button size="icon" variant="ghost" aria-label="删除记录" onClick={()=>remove("record",r.id,r.name)}><Trash2/></Button></div></TableCell></TableRow>)}</TableBody></Table>:<p className="helper">还没有保存的真实训练记录。</p>}</Panel></div>;
}
