"use client";
import {useState} from "react";
import {zhCN} from "date-fns/locale";
import {Calendar,CalendarDayButton} from "@/components/ui/calendar";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Plus,Flag,Timer,Trash2,Pencil,CalendarDays} from "lucide-react";
import {Data,Plan,RecordItem,dateKey,dateOf,fmt,total} from "@/lib/rox";
import {Button,Panel,Field,Pick,EmptyBox,Stat} from "./ui";
export default function CalendarView({data,save,onRecord,remove,onManual}:{data:Data;save:(kind:string,data:any)=>Promise<boolean>;onRecord:(r:RecordItem)=>void;remove:(kind:string,id:string,title:string)=>void;onManual:()=>void}){
 const [day,setDay]=useState(new Date()),[month,setMonth]=useState(new Date()),[edit,setEdit]=useState<Plan|null>(null),[busy,setBusy]=useState(false);
 const date=dateKey(day),monthKey=dateKey(month).slice(0,7),records=data.records.filter(r=>r.date===date),plans=data.plans.filter(p=>p.date===date),monthRecords=data.records.filter(r=>r.date.startsWith(monthKey)&&r.mode!=="judge"),monthPlans=data.plans.filter(p=>p.date.startsWith(monthKey));
 function add(){setEdit({id:crypto.randomUUID(),date,title:"",kind:"训练",minutes:45,notes:"",done:false})}
 return <div><div className="stats-grid three"><Stat label="本月已记录训练" value={`${monthRecords.length} 次`} detail={`${new Set(monthRecords.map(r=>r.date)).size} 个训练日`}/><Stat label="本月训练用时" value={`${Math.round(monthRecords.reduce((n,r)=>n+r.seconds,0)/60)} 分钟`} detail="按实际记录统计，不含裁判记录"/><Stat label="日历安排完成" value={`${monthPlans.filter(p=>p.done).length} / ${monthPlans.length}`} detail="训练、恢复与比赛安排"/></div><div className="calendar-layout"><Panel title="训练日历" action={<Button onClick={add}><Plus/>添加安排</Button>}><div className="calendar-legend"><span><i className="legend-dot station"/>已记录训练</span><span><i className="legend-dot run"/>训练 / 恢复安排</span><span><i className="legend-dot zone"/>比赛</span></div><Calendar locale={zhCN} mode="single" selected={day} onSelect={v=>{if(v)setDay(v)}} month={month} onMonthChange={setMonth} weekStartsOn={1} className="training-calendar" components={{DayButton:props=>{const k=dateKey(props.day.date),rs=data.records.filter(r=>r.date===k),ps=data.plans.filter(p=>p.date===k);return <CalendarDayButton {...props}><span>{props.day.date.getDate()}</span><div className="day-markers" aria-hidden="true">{rs.length>0&&<i className="station"/>}{ps.some(p=>p.kind!=="比赛")&&<i className="run"/>}{ps.some(p=>p.kind==="比赛")&&<i className="zone"/>}</div></CalendarDayButton>}}}/><div className="row calendar-bottom"><Button variant="outline" onClick={()=>{setDay(new Date());setMonth(new Date())}}>回到今天</Button><span className="helper">点击日期查看训练和赛事</span></div></Panel><aside><Panel title={day.toLocaleDateString("zh-CN",{month:"long",day:"numeric",weekday:"long"})} eyebrow="DAY PLAN" action={<span className="tag">{records.length+plans.length} 项</span>}>
 {records.length+plans.length===0?<EmptyBox title="给这一天留个安排" text="加入训练、恢复日或目标比赛。" action={<Button variant="outline" onClick={add}><Plus/>添加安排</Button>}/>:<div className="day-agenda">{plans.map(p=><div className="agenda-item" key={p.id}><Checkbox aria-label={`标记${p.title}完成`} checked={p.done} onCheckedChange={v=>save("plan",{...p,done:!!v})}/><div className={p.done?"done-text":""}><span className={`tag ${p.kind==="比赛"?"blue":"green"}`}>{p.kind}</span><h3>{p.title}</h3><p>{p.minutes?`${p.minutes} 分钟 · `:""}{p.notes||"暂无备注"}</p></div><div className="agenda-controls"><Button size="icon" variant="ghost" aria-label="编辑安排" onClick={()=>setEdit(p)}><Pencil/></Button><Button size="icon" variant="ghost" aria-label="删除安排" onClick={()=>remove("plan",p.id,p.title)}><Trash2/></Button></div></div>)}{records.map(r=><button key={r.id} className="agenda-record" onClick={()=>onRecord(r)}><span className="agenda-icon"><Timer/></span><div><small>{r.mode==="judge"?"裁判记录":"已记录训练"}</small><h3>{r.name}</h3><p>{r.division} · {r.complete?"已完成":"未完成"}</p></div><b>{fmt(total(r))}</b></button>)}</div>}
 </Panel><Button variant="outline" className="w-full" onClick={onManual}><Plus/>补录训练成绩</Button><div className="calendar-note"><CalendarDays/><p>在「赛事与排名」收藏比赛后，比赛会进入这个日历。多日赛事将按开赛日加入，可改成你的实际参赛日。</p></div></aside></div>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!busy)setEdit(null)}}><DialogContent><DialogHeader><DialogTitle>日历安排</DialogTitle><DialogDescription>安排与训练成绩分别保存，勾选完成不会生成计时成绩。</DialogDescription></DialogHeader>{edit&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);const ok=await save("plan",edit);setBusy(false);if(ok)setEdit(null)}} className="form-stack"><Field label="标题"><Input required maxLength={160} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} placeholder="例如：雪橇推专项训练"/></Field><div className="form-grid"><Field label="日期"><Input required type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></Field><Field label="类型"><Pick value={edit.kind} label="安排类型" options={["训练","比赛","恢复"]} onChange={v=>setEdit({...edit,kind:v as Plan["kind"]})}/></Field></div><Field label="预计用时（分钟）"><Input type="number" min="0" max="1440" value={edit.minutes} onChange={e=>setEdit({...edit,minutes:Number(e.target.value)})}/></Field><Field label="训练内容 / 备注"><Textarea maxLength={4000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="记录组数、距离、强度或赛事信息"/></Field><Button type="submit" disabled={busy}>{busy?"正在保存…":"保存安排"}</Button></form>}</DialogContent></Dialog></div>;
}
