"use client";
import {useState} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Globe2,MapPin,CalendarPlus,Target,Trophy,Plus,Check,Trash2,Search} from "lucide-react";
import {toast} from "sonner";
import {Data,RACES,CHECKED,DEFAULT_GOAL,STATIONS,DIVISIONS,Benchmark,dateKey,fmt,parse} from "@/lib/rox";
import {Button,Panel,Pick,Field,EmptyBox,External} from "./ui";
export default function RacesView({data,save,city,setCity,remove,onAnalyze}:{data:Data;save:(kind:string,data:any)=>Promise<boolean>;city:string;setCity:(city:string)=>void;remove:(kind:string,id:string,title:string)=>void;onAnalyze:()=>void}){
 const [scope,setScope]=useState("local"),[region,setRegion]=useState("all"),[country,setCountry]=useState("all"),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({name:"",date:dateKey(),division:DIVISIONS[0],source:"",time:"",notes:"",splits:{} as {[k:string]:string}});
 const visible=RACES.filter(r=>(scope==="global"||r.city===city)&&(region==="all"||r.region===region)&&(country==="all"||r.country===country)&&(`${r.city} ${r.country} ${r.id}`.toLowerCase().includes(query.toLowerCase()))),countries=[...new Set(RACES.map(r=>r.country))],cities=[...new Set(RACES.map(r=>r.city))];
 async function saveBenchmark(e:React.FormEvent){e.preventDefault();const seconds=parse(form.time),splits:{[k:string]:number}={};if(!Number.isFinite(seconds)||seconds<=0)return toast.error("总时间请填写为 分:秒 或 时:分:秒。");for(const [key,value] of Object.entries(form.splits)){if(!value.trim())continue;const n=parse(value);if(!Number.isFinite(n))return toast.error("分段时间格式不正确。");splits[key]=n;}if(Object.values(splits).reduce((a,b)=>a+b,0)>seconds+1)return toast.error("分段合计不能超过总成绩，请核对来源。");setBusy(true);const ok=await save("benchmark",{id:crypto.randomUUID(),name:form.name,date:form.date,division:form.division,source:form.source,seconds,splits,notes:form.notes});setBusy(false);if(ok){setOpen(false);setForm({...form,name:"",source:"",time:"",splits:{},notes:""})}}
 return <Tabs defaultValue="events" className="race-tabs"><TabsList className="mode-tabs"><TabsTrigger value="events"><CalendarPlus/>赛事日历</TabsTrigger><TabsTrigger value="rank"><Trophy/>全球排名与对标</TabsTrigger></TabsList><TabsContent value="events"><div className="race-intro"><div><span className="eyebrow">FIND YOUR NEXT RACE</span><h2>下一站，向终点出发。</h2><p>选择所在地，收藏比赛，开始你的备赛倒计时。</p></div><Globe2 className="race-globe" aria-hidden="true"/></div><div className="race-filters"><Tabs value={scope} onValueChange={v=>{setScope(v);setRegion("all");setCountry("all")}}><TabsList><TabsTrigger value="local">所在地</TabsTrigger><TabsTrigger value="global">全球</TabsTrigger></TabsList></Tabs>{scope==="local"?<Pick label="所在地" value={city} options={cities} onChange={setCity}/>:<><Pick label="洲" value={region} onChange={v=>{setRegion(v);setCountry("all")}} options={[{value:"all",label:"所有洲"},"亚太","欧洲","北美","南美","非洲"]}/><Pick label="国家地区" value={country} onChange={setCountry} options={[{value:"all",label:"所有国家 / 地区"},...countries]}/></>}<div className="search-field"><Search size={17}/><Input aria-label="搜索赛事城市" placeholder="搜索城市或英文名称" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="source-line"><span>已核对赛历 · {CHECKED} · 收录 {RACES.length} 场 · 非实时更新</span><External href="https://hyroxuk.com/find-my-race/">官方完整赛历</External></div>
 <div className="race-grid">{visible.map(r=>{const id=`race-${r.id}-${r.date}`,saved=data.plans.some(p=>p.id===id),today=new Intl.DateTimeFormat("en-CA",{timeZone:r.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),ended=r.end<today;return <article className={`race-card ${r.city===city?"local-race":""}`} key={r.id}><div className="row space-between"><span className="tag">{r.region} · {r.country}</span>{r.city===city&&<span className="local-label"><MapPin size={14}/>所在地</span>}</div><div className="race-date"><span>{r.date.slice(5,7)}<small>月</small></span><b>{r.date.slice(8)}<small>日起</small></b></div><h3>HYROX {r.city}</h3><p>{r.date} — {r.end}</p><small className="muted">举办地日期 · {ended?"已结束":r.date<=today?"赛事期间":"即将举行"}</small><div className="race-card-actions"><Button variant={saved?"secondary":"outline"} disabled={saved} onClick={()=>save("plan",{id,date:r.date,title:`HYROX ${r.city}`,kind:"比赛",minutes:0,notes:`赛期 ${r.date} — ${r.end}（${r.timezone}）。请按自己的实际参赛日调整。`,done:false,source:r.url})}>{saved?<Check/>:<CalendarPlus/>}{saved?"已加入日历":"加入日历"}</Button><Button variant="ghost" size="icon" aria-label={`将${r.city}设为备赛目标`} onClick={()=>save("goal",{...(data.goal||DEFAULT_GOAL),title:`HYROX ${r.city}`,date:r.date})}><Target/></Button></div><External href={r.url}>查看官方赛事信息</External></article>})}</div>{!visible.length&&<EmptyBox title="当前筛选下暂无收录赛事" text="这不代表当地没有比赛。可以切换全球，或查看官方完整赛历。"/>}<p className="helper">赛历根据官方页面人工核对，可能调整。日期按比赛举办地显示；请在报名和出行前打开官方页面确认。赛事加入日历后，可调整为自己的参赛日。</p></TabsContent>
 <TabsContent value="rank"><div className="rank-layout"><Panel title="官方全球成绩与排名" eyebrow="OFFICIAL RESULTS"><div className="ranking-icon"><Trophy/></div><h3 className="section-statement">找到你的比赛、组别和运动员。</h3><p className="muted">官方成绩站可查询赛事成绩和排名。本工具尚未接入实时排名数据，不估算你的全球名次。</p><div className="rank-links"><Button asChild><a href="https://hyroxresults.com/" target="_blank" rel="noopener noreferrer">打开官方成绩与排名<ArrowIcon/></a></Button><External href="https://hyroxuk.com/">官方入口来源</External></div><div className="notice">比较时请核对赛季、性别、年龄组、单人 / 双人和公开 / 专业组。世界纪录、年龄组排名与单场名次是不同指标。</div></Panel><Panel title="我的运动员参考库" action={<Button onClick={()=>setOpen(true)}><Plus/>添加成绩</Button>}><p className="helper">从官方成绩页抄录运动员的总时间和单项分段，并保存来源链接，即可在「成绩分析」中对比。</p>{data.benchmarks.length?<div className="benchmark-list">{data.benchmarks.map(b=><div key={b.id}><div><h3>{b.name}</h3><small>{b.division} · {b.date}</small><External href={b.source}>用户录入 · 来源</External></div><strong>{fmt(b.seconds,true)}</strong><Button variant="ghost" size="icon" aria-label="删除参考成绩" onClick={()=>remove("benchmark",b.id,b.name)}><Trash2/></Button></div>)}</div>:<EmptyBox title="还没有参考成绩" text="参考库为空，真实运动员数据需要附可核对的来源。"/>}<Button variant="outline" className="w-full" onClick={onAnalyze}>进入单项成绩对比</Button></Panel></div><Panel title="产品参考与数据来源"><div className="reference-grid"><div><h3>ROXFIT</h3><p>参考分段配速、比赛目标与赛后运动员对比的工作方式。</p><External href="https://www.roxfit.app/how-it-works/">查看开发者功能介绍</External></div><div><h3>TrainRox</h3><p>参考备赛目标、训练安排与历史记录的衔接方式。</p><External href="https://play.google.com/store/apps/details?id=com.stellarapps.workout">查看开发者商店介绍</External></div><div><h3>HYROX 官方</h3><p>赛事时间和基础赛制取自官方；本工具独立开发，不代表官方。</p><External href="https://hyroxuk.com/rulebook/">规则与动作标准</External></div></div></Panel></TabsContent>
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="large-dialog"><DialogHeader><DialogTitle>添加运动员参考成绩</DialogTitle><DialogDescription>保留赛事、组别和原始成绩链接。空白分段不会被当作 0 秒。</DialogDescription></DialogHeader><form onSubmit={saveBenchmark} className="form-stack"><div className="form-grid"><Field label="运动员姓名"><Input required maxLength={160} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="比赛日期"><Input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="组别"><Pick label="运动员组别" value={form.division} options={DIVISIONS} onChange={v=>setForm({...form,division:v})}/></Field><Field label="总成绩（含罚时）"><Input required placeholder="01:05:30" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></Field></div><Field label="成绩来源链接（HTTPS）"><Input required type="url" pattern="https://.*" placeholder="https://…" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><div className="form-grid">{[{id:"run",name:"跑步合计"},...STATIONS,{id:"zone",name:"转换区合计"}].map(s=><Field label={s.name+"（分:秒）"} key={s.id}><Input placeholder="选填，例如 04:30" value={form.splits[s.id]||""} onChange={e=>setForm({...form,splits:{...form.splits,[s.id]:e.target.value}})}/></Field>)}</div><Field label="赛事、年龄组及备注"><Textarea value={form.notes} maxLength={4000} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Button type="submit" disabled={busy}>{busy?"正在保存…":"保存参考成绩"}</Button></form></DialogContent></Dialog></Tabs>;
}
function ArrowIcon(){return <span aria-hidden="true">↗</span>}
