"use client";
import {useState,useEffect} from "react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Checkbox} from "@/components/ui/checkbox";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from "@/components/ui/collapsible";
import {Save,ChevronDown,Download} from "lucide-react";
import {RecordItem,STATIONS,DIVISIONS,fmt,parse,dateKey,download} from "@/lib/rox";
import {Button,Field,Pick} from "./ui";
import {toast} from "sonner";
export function manualRecord():RecordItem{return {id:crypto.randomUUID(),date:dateKey(),name:"全程模拟",mode:"full",division:DIVISIONS[0],station:"",athlete:"自己",load:"",target:100,count:0,seconds:0,penalty:0,splits:[],audit:[],complete:true,rpe:0,notes:"",source:"手工补录"}}
export default function RecordForm({record,onClose,onSave}:{record:RecordItem|null;onClose:()=>void;onSave:(r:RecordItem)=>Promise<boolean>}){
 const [r,setR]=useState<RecordItem|null>(record),[time,setTime]=useState(""),[busy,setBusy]=useState(false),[fields,setFields]=useState<{[k:string]:string}>({});
 useEffect(()=>{setR(record);setTime(record&&record.seconds?fmt(record.seconds,true):"");setFields({})},[record]);
 if(!r)return null;const manual=r.source==="手工补录",single=r.mode==="single"||r.mode==="judge",station=STATIONS.find(s=>s.id===r.station)||STATIONS[0];
 async function submit(e:React.FormEvent){e.preventDefault();if(!r)return;const seconds=manual?parse(time):r.seconds;if(!Number.isFinite(seconds)||seconds<=0)return toast.error("请填写有效时间，例如 01:25:30。");let splits=r.splits;if(manual&&r.mode==="single")splits=[{id:r.station,name:station.name,type:"station",target:r.target,seconds,end:seconds}];else if(manual&&Object.values(fields).some(v=>v.trim())){let end=0;splits=[];for(const s of [{id:"run-total",name:"跑步合计",type:"run"},...STATIONS.map(s=>({...s,type:"station"})),{id:"zone-total",name:"转换区合计",type:"zone"}]){const value=fields[s.id];if(!value?.trim())continue;const n=parse(value);if(!Number.isFinite(n))return toast.error(`请检查${s.name}时间。`);end+=n;splits.push({id:s.id,name:s.name,type:s.type as any,seconds:n,end})}}if(splits.reduce((a,b)=>a+b.seconds,0)>seconds+1)return toast.error("分段合计不能超过计时总用时。");setBusy(true);const ok=await onSave({...r,seconds,splits,load:r.load.trim()||"负重未填写"});setBusy(false);if(ok)onClose()}
 return <Dialog open={!!record} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="large-dialog"><DialogHeader><DialogTitle>{manual?"补录训练成绩":"训练记录"}</DialogTitle><DialogDescription>保存后可在日历和成绩分析中查看。原始计时不含人工罚时，最终成绩会单独相加。</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit}><Field label="训练名称"><Input required maxLength={160} value={r.name} onChange={e=>setR({...r,name:e.target.value})}/></Field><div className="form-grid"><Field label="日期"><Input required type="date" value={r.date} onChange={e=>setR({...r,date:e.target.value})}/></Field><Field label="运动员"><Input required maxLength={160} value={r.athlete} onChange={e=>setR({...r,athlete:e.target.value})}/></Field><Field label="模式"><Pick value={r.mode} label="训练模式" disabled={!manual} options={[{value:"full",label:"全程模拟"},{value:"single",label:"单站训练"},{value:"race",label:"比赛日"},...(r.mode==="judge"?[{value:"judge",label:"裁判记录"}]:[])]} onChange={v=>setR({...r,mode:v as RecordItem["mode"],station:v==="single"?"ski":"",target:v==="single"?1000:100})}/></Field><Field label="组别"><Pick value={r.division} label="比赛组别" options={DIVISIONS} onChange={v=>setR({...r,division:v})}/></Field>{single&&<><Field label="功能站"><Pick disabled={!manual} label="功能站" value={r.station} options={STATIONS.map(s=>({value:s.id,label:s.name}))} onChange={v=>{const s=STATIONS.find(s=>s.id===v)!;setR({...r,station:v,target:s.target})}}/></Field><Field label={`目标（${station.unit}）`}><Input type="number" min="1" max="10000" readOnly={!manual} value={r.target} onChange={e=>setR({...r,target:Number(e.target.value)})}/></Field></>}<Field label="计时用时（不含罚时）"><Input required placeholder="01:25:30 或 05:30" value={time} readOnly={!manual} onChange={e=>setTime(e.target.value)}/></Field><Field label="人工罚时（秒）"><Input type="number" min="0" max="86400" readOnly={r.mode==="judge"} value={r.penalty} onChange={e=>setR({...r,penalty:Number(e.target.value)})}/></Field></div><Field label="器械、负重与场地标准"><Input maxLength={300} value={r.load} onChange={e=>setR({...r,load:e.target.value})} placeholder="写明负重、地面与距离，方便以后比较"/></Field><div className="form-grid"><Field label="主观强度 RPE（0–10）"><Input type="number" min="0" max="10" step="0.5" value={r.rpe} onChange={e=>setR({...r,rpe:Number(e.target.value)})}/></Field><label className="row checkbox-field"><Checkbox checked={r.complete} disabled={!manual} onCheckedChange={v=>setR({...r,complete:!!v})}/>完整完成规定内容</label></div>
 {manual&&!single&&<Collapsible><CollapsibleTrigger asChild><Button variant="outline" type="button">补充分段时间（选填）<ChevronDown/></Button></CollapsibleTrigger><CollapsibleContent><div className="form-grid split-form">{[{id:"run-total",name:"跑步合计"},...STATIONS,{id:"zone-total",name:"转换区合计"}].map(s=><Field key={s.id} label={`${s.name}（分:秒）`}><Input value={fields[s.id]||""} placeholder="未记录可留空" onChange={e=>setFields({...fields,[s.id]:e.target.value})}/></Field>)}</div></CollapsibleContent></Collapsible>}
 {r.splits.length>0&&<Collapsible><CollapsibleTrigger asChild><Button variant="outline" type="button">查看 {r.splits.length} 个计时分段<ChevronDown/></Button></CollapsibleTrigger><CollapsibleContent><Table><TableHeader><TableRow><TableHead>分段</TableHead><TableHead>用时</TableHead></TableRow></TableHeader><TableBody>{r.splits.map((s,i)=><TableRow key={s.id+String(i)}><TableCell>{s.name}</TableCell><TableCell className="mono">{fmt(s.seconds)}</TableCell></TableRow>)}</TableBody></Table></CollapsibleContent></Collapsible>}
 {r.audit.length>0&&<div className="notice">已保留 {r.audit.length} 条操作记录，含无效动作、罚时和撤销。可导出完整记录核对。</div>}<Field label="备注 / 复盘"><Textarea maxLength={4000} value={r.notes} onChange={e=>setR({...r,notes:e.target.value})} placeholder="例如：第 6 段跑步掉速；墙球需要改善节奏"/></Field><div className="row space-between"><Button variant="outline" type="button" onClick={()=>download(`rox-record-${r.date}.json`,JSON.stringify(r,null,2))}><Download/>导出原始记录</Button><Button disabled={busy||!r.name.trim()} type="submit"><Save/>{busy?"正在保存…":"保存训练记录"}</Button></div></form></DialogContent></Dialog>;
}
