import {getChatGPTUser} from "../../chatgpt-auth";
import {database} from "@/db/raw";
import {z} from "zod";
const str=z.string().max(4000),id=z.string().min(1).max(100),num=z.number().finite().min(0).max(864000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v)));
const split=z.object({id,name:str,type:z.enum(["run","station","zone"]),target:num.optional(),seconds:num,end:num});
const audit=z.object({id,type:z.enum(["valid","invalid","penalty","undo"]),amount:num,reason:str,at:z.number().finite().min(0),targetId:id.optional()});
const schemas={record:z.object({id,date,name:str,mode:z.enum(["full","single","race","judge"]),division:str,station:str,athlete:str,load:str,target:num,count:num,seconds:num,penalty:num,splits:z.array(split).max(100),audit:z.array(audit).max(5000),complete:z.boolean(),rpe:z.number().min(0).max(10),notes:str,source:str}),plan:z.object({id,date,title:z.string().min(1).max(160),kind:z.enum(["训练","比赛","恢复"]),minutes:num,notes:str,done:z.boolean(),source:str.optional()}),goal:z.object({id,title:z.string().min(1).max(160),date:date.or(z.literal("")),division:str,seconds:num,run:num,stations:z.array(num).length(8),zone:num,checklist:z.array(str).max(30)}),benchmark:z.object({id,name:z.string().min(1).max(160),date,division:str,source:z.string().url().max(1000).refine(v=>v.startsWith("https://")),seconds:num,splits:z.record(num),notes:str})};
export const dynamic="force-dynamic";
const reply=(v:unknown,status=200)=>Response.json(v,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:"请登录后读取记录。"},401);try{const r=await database().prepare("SELECT kind,payload FROM rox_records WHERE user_id=? ORDER BY updated_at DESC").bind(user.userId).all<{kind:string;payload:string}>();const data:{records:unknown[];plans:unknown[];benchmarks:unknown[];goal:unknown}={records:[],plans:[],benchmarks:[],goal:null};for(const x of r.results){const v=JSON.parse(x.payload);if(x.kind==="record")data.records.push(v);else if(x.kind==="plan")data.plans.push(v);else if(x.kind==="benchmark")data.benchmarks.push(v);else if(x.kind==="goal")data.goal=v;}return reply(data)}catch(e){console.error(e);return reply({error:"读取失败，请重试。"},503)}}
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return reply({error:"请登录后保存记录。"},401);if(req.headers.get("origin")&&req.headers.get("origin")!==new URL(req.url).origin)return reply({error:"请求来源不匹配。"},403);try{const raw=await req.text();if(raw.length>500000)return reply({error:"数据过大。"},413);const body=JSON.parse(raw),kind=body.kind as keyof typeof schemas;if(!schemas[kind])return reply({error:"未知记录类型。"},400);const parsed=schemas[kind].safeParse(body.data);if(!parsed.success)return reply({error:"请检查日期、时间和必填信息。"},400);await database().prepare("INSERT INTO rox_records (user_id,kind,id,payload,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,kind,id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").bind(user.userId,kind,kind==="goal"?"current":parsed.data.id,JSON.stringify(parsed.data),Date.now()).run();return reply({ok:true})}catch(e){console.error(e);return reply({error:"保存失败，输入已保留，请重试。"},503)}}
export async function DELETE(req:Request){const user=await getChatGPTUser();if(!user)return reply({error:"请先登录。"},401);if(req.headers.get("origin")&&req.headers.get("origin")!==new URL(req.url).origin)return reply({error:"请求来源不匹配。"},403);const p=new URL(req.url).searchParams,kind=p.get("kind"),id=p.get("id");if(!kind||!id||!["record","plan","benchmark"].includes(kind))return reply({error:"无效请求。"},400);try{await database().prepare("DELETE FROM rox_records WHERE user_id=? AND kind=? AND id=?").bind(user.userId,kind,id).run();return reply({ok:true})}catch(e){console.error(e);return reply({error:"删除失败，请重试。"},503)}}
